spring:
  application:
    name: wms-erp
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:lotDb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto=validate: true
        ddl-auto: validate
server:
  port: 8081
jwt:
  token: test

---
spring:
  profiles: test
  application:
    name: wms-erp
  datasource:
    url: jdbc:postgresql:lotdb?currentSchema=lotdb
    driverClassName: org.postgresql.Driver
    username: ${erp_database_userName}
    password: ${erp_database_password}
  flyway:
    schemas: lotdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto=validate: true
server:
  port: 8081
jwt:
  token: ${erp_jwt_token}

---
spring:
  profiles: prod
  application:
    name: wms-erp
  datasource:
    url: jdbc:postgresql:lotdb?currentSchema=lotdb
    driverClassName: org.postgresql.Driver
    username: ${erp_database_userName}
    password: ${erp_database_password}
  flyway:
    schemas: lotdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto=validate: true
server:
  port: 8081
jwt:
  token: ${erp_jwt_token}
